#include "Containers.h"

namespace GStreamer
{
/*
const std::vector< int > vMessageType = { 
  GST_MESSAGE_UNKNOWN,
  GST_MESSAGE_EOS,
  GST_MESSAGE_ERROR,
  GST_MESSAGE_WARNING,
  GST_MESSAGE_INFO,
  GST_MESSAGE_TAG,
  GST_MESSAGE_BUFFERING,
  GST_MESSAGE_STATE_CHANGED,
  GST_MESSAGE_STATE_DIRTY,
  GST_MESSAGE_STEP_DONE,
  GST_MESSAGE_CLOCK_PROVIDE,
  GST_MESSAGE_CLOCK_LOST,
  GST_MESSAGE_NEW_CLOCK,
  GST_MESSAGE_STRUCTURE_CHANGE,
  GST_MESSAGE_STREAM_STATUS,
  GST_MESSAGE_APPLICATION,
  GST_MESSAGE_ELEMENT,
  GST_MESSAGE_SEGMENT_START,
  GST_MESSAGE_SEGMENT_DONE,
  GST_MESSAGE_DURATION_CHANGED,
  GST_MESSAGE_LATENCY,
  GST_MESSAGE_ASYNC_START,
  GST_MESSAGE_ASYNC_DONE,
  GST_MESSAGE_REQUEST_STATE,
  GST_MESSAGE_STEP_START,
  GST_MESSAGE_QOS,
  GST_MESSAGE_PROGRESS,
  GST_MESSAGE_TOC,
  GST_MESSAGE_RESET_TIME,
  GST_MESSAGE_STREAM_START,
  GST_MESSAGE_NEED_CONTEXT,
  GST_MESSAGE_HAVE_CONTEXT,
  GST_MESSAGE_EXTENDED,
  GST_MESSAGE_DEVICE_ADDED,
  GST_MESSAGE_DEVICE_REMOVED,
  GST_MESSAGE_ANY };
*/
}
